name: Nightly
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  publish_nightly:
    uses: rancher-sandbox/highlander-reusable-workflows/.github/workflows/operator-with-latest-rancher-build.yaml@a8c5ab146fed1a6ba07b5947d045fa05593b8173 # main
    permissions:
      contents: read
      packages: write
    with:
      operator_name: eks-operator
      operator_commit: ${{ github.sha }}
